
# The log file location   
log:
filename: "LedgeSparks.log"

# All the databases used by the system
databases:
  dev: "data/db.sqlite"
  stage: ""
  prod: ""

models:
  mainDB:
    - Bill
    - Salience
